spring:
  datasource:
    platform:



#datasource:
#  name: DruidDataSource
#  type: com.alibaba.druid.pool.DruidDataSource
#  driver-class-name: com.mysql.jdbc.Driver
#  url: jdbc:mysql://39.108.130.98:30061/union?useUnicode=true&characterEncoding=utf8&&useSSL=false
#  username: root
#  password: 30Q8OtgB9I
